# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild was generated by g-octave

EAPI="3"

G_OCTAVE_CAT="main"

inherit g-octave

DESCRIPTION="Non-linear optimization toolkit."
HOMEPAGE="http://octave.sf.net"

LICENSE="GPL-2 FDL-1.3"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND="${DEPEND}
	>=g-octave/miscellaneous-1.0.10
	>=g-octave/struct-1.0.9
	>=sci-mathematics/octave-2.9.7"
