# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild was generated by g-octave

EAPI="3"

G_OCTAVE_CAT="extra"

inherit g-octave

DESCRIPTION="Collection of routines to save data in different graphical formats."
HOMEPAGE="None"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND="
	sys-apps/sed
	app-shells/bash
	>=sci-visualization/opendx-4.3.2"
RDEPEND="${DEPEND}
	>=sci-mathematics/octave-3.0.0"
