# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild was generated by g-octave

EAPI="3"

G_OCTAVE_CAT="extra"

inherit g-octave

DESCRIPTION="socket implementation of a tcl-octave connection"
HOMEPAGE="http://octave.sf.net"

LICENSE="public-domain"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND="
	dev-lang/tcl"
RDEPEND="${DEPEND}
	>=sci-mathematics/octave-2.9.7"
