# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild was generated by g-octave

EAPI="3"

G_OCTAVE_CAT="extra"

inherit g-octave

DESCRIPTION="A statistics and machine learning toolbox for Octave and Matlab for da..."
HOMEPAGE="http://biosig-consulting.com/matlab/NaN"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64 ~amd64 ~ppc ~ppc64 ~x86 ~x86 ~x86"
IUSE=""

DEPEND=""
RDEPEND="${DEPEND}
	>sci-mathematics/octave-2.9.0"
