# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild was generated by g-octave

EAPI="3"

G_OCTAVE_CAT="main"

inherit g-octave

DESCRIPTION="Additional manipulation functions"
HOMEPAGE="http://octave.sf.net"

LICENSE="BSD GPL-2 GPL-3 public-domain"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="dev-libs/libpcre"
RDEPEND="${DEPEND}
	>=sci-mathematics/octave-2.9.7"
