# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild was generated by g-octave

EAPI="3"

G_OCTAVE_CAT="main"

inherit g-octave

DESCRIPTION="Additional manipulation functions"
HOMEPAGE="http://octave.sf.net"

LICENSE="GPLv3+, modified BSD, public domain"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND="dev-libs/libpcre"
RDEPEND="${DEPEND}
	>=sci-mathematics/octave-3.6.0"
