# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild was generated by g-octave

EAPI="3"

G_OCTAVE_CAT="main"

inherit g-octave

DESCRIPTION="Physical Constants from Atomic & Molecular Physics, taken from NIST da..."
HOMEPAGE="http://octave.sf.net"

LICENSE="GPLv3+"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND="${DEPEND}
	>=g-octave/miscellaneous-1.2.0"
