# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild was generated by g-octave

EAPI="3"

G_OCTAVE_CAT="extra"

inherit g-octave

DESCRIPTION="Stochastic concepts and maximum entropy methods for time series analys..."
HOMEPAGE="http://hci.tugraz.at/~schloegl/matlab/tsa"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND="${DEPEND}
	>=g-octave/NaN-1.0.0
	>=sci-mathematics/octave-2.9.7"
