# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild was generated by g-octave

EAPI="3"

G_OCTAVE_CAT="main"

inherit g-octave

DESCRIPTION="Miscellaneous tools including waitbar, xml tools, etc"
HOMEPAGE="http://octave.sf.net"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND="sys-libs/libtermcap-compat
	sci-calculators/units"
RDEPEND="${DEPEND}
	>=sci-mathematics/octave-2.9.16"
