# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild was generated by g-octave

EAPI="3"

G_OCTAVE_CAT="main"

inherit g-octave

DESCRIPTION="Computer-Aided Control System Design (CACSD) Tools for GNU Octave, bas..."
HOMEPAGE="http://octave.sf.net, http://www.slicot.org"

LICENSE="GPLv3+"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND="${DEPEND}
	>=sci-mathematics/octave-3.6.0"
